version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    #este servicio de tests esta bueno porque deja correr ambos containers, pero, no te deja los shortcut de p q que te aparecen al correr el test (video 80 muuestra otra version como si te deja)
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]